var DATA = [
  {
    "iso":"AF",
    "country":"Afghanistan",
    "capital":"Kabul",
    "tld":".af",
    "currencycode":"AFN",
    "currencyname":"Afghani",
    "phone":"93",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fa-AF,ps,uz-AF,tk"
  },
  {
    "iso":"AX",
    "country":"Aland Islands",
    "capital":"Mariehamn",
    "tld":".ax",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"+358-18",
    "postal code format":"",
    "postal code regex":"",
    "languages":"sv-AX"
  },
  {
    "iso":"AL",
    "country":"Albania",
    "capital":"Tirana",
    "tld":".al",
    "currencycode":"ALL",
    "currencyname":"Lek",
    "phone":"355",
    "postal code format":"",
    "postal code regex":"",
    "languages":"sq,el"
  },
  {
    "iso":"DZ",
    "country":"Algeria",
    "capital":"Algiers",
    "tld":".dz",
    "currencycode":"DZD",
    "currencyname":"Dinar",
    "phone":"213",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-DZ"
  },
  {
    "iso":"AS",
    "country":"American Samoa",
    "capital":"Pago Pago",
    "tld":".as",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-684",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-AS,sm,to"
  },
  {
    "iso":"AD",
    "country":"Andorra",
    "capital":"Andorra la Vella",
    "tld":".ad",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"376",
    "postal code format":"AD###",
    "postal code regex":"^(?:AD)*(\\d{3})$",
    "languages":"ca"
  },
  {
    "iso":"AO",
    "country":"Angola",
    "capital":"Luanda",
    "tld":".ao",
    "currencycode":"AOA",
    "currencyname":"Kwanza",
    "phone":"244",
    "postal code format":"",
    "postal code regex":"",
    "languages":"pt-AO"
  },
  {
    "iso":"AI",
    "country":"Anguilla",
    "capital":"The Valley",
    "tld":".ai",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-264",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-AI"
  },
  {
    "iso":"AQ",
    "country":"Antarctica",
    "capital":"",
    "tld":".aq",
    "currencycode":"",
    "currencyname":"",
    "phone":"",
    "postal code format":"",
    "postal code regex":"",
    "languages":""
  },
  {
    "iso":"AG",
    "country":"Antigua and Barbuda",
    "capital":"St. John's",
    "tld":".ag",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-268",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-AG"
  },
  {
    "iso":"AR",
    "country":"Argentina",
    "capital":"Buenos Aires",
    "tld":".ar",
    "currencycode":"ARS",
    "currencyname":"Peso",
    "phone":"54",
    "postal code format":"@####@@@",
    "postal code regex":"^([A-Z]\\d{4}[A-Z]{3})$",
    "languages":"es-AR,en,it,de,fr,gn"
  },
  {
    "iso":"AM",
    "country":"Armenia",
    "capital":"Yerevan",
    "tld":".am",
    "currencycode":"AMD",
    "currencyname":"Dram",
    "phone":"374",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"hy"
  },
  {
    "iso":"AW",
    "country":"Aruba",
    "capital":"Oranjestad",
    "tld":".aw",
    "currencycode":"AWG",
    "currencyname":"Guilder",
    "phone":"297",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl-AW,es,en"
  },
  {
    "iso":"AU",
    "country":"Australia",
    "capital":"Canberra",
    "tld":".au",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"61",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"en-AU"
  },
  {
    "iso":"AT",
    "country":"Austria",
    "capital":"Vienna",
    "tld":".at",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"43",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"de-AT,hr,hu,sl"
  },
  {
    "iso":"AZ",
    "country":"Azerbaijan",
    "capital":"Baku",
    "tld":".az",
    "currencycode":"AZN",
    "currencyname":"Manat",
    "phone":"994",
    "postal code format":"AZ ####",
    "postal code regex":"^(?:AZ)*(\\d{4})$",
    "languages":"az,ru,hy"
  },
  {
    "iso":"BS",
    "country":"Bahamas",
    "capital":"Nassau",
    "tld":".bs",
    "currencycode":"BSD",
    "currencyname":"Dollar",
    "phone":"+1-242",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-BS"
  },
  {
    "iso":"BH",
    "country":"Bahrain",
    "capital":"Manama",
    "tld":".bh",
    "currencycode":"BHD",
    "currencyname":"Dinar",
    "phone":"973",
    "postal code format":"####|###",
    "postal code regex":"^(\\d{3}\\d?)$",
    "languages":"ar-BH,en,fa,ur"
  },
  {
    "iso":"BD",
    "country":"Bangladesh",
    "capital":"Dhaka",
    "tld":".bd",
    "currencycode":"BDT",
    "currencyname":"Taka",
    "phone":"880",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"bn-BD,en"
  },
  {
    "iso":"BB",
    "country":"Barbados",
    "capital":"Bridgetown",
    "tld":".bb",
    "currencycode":"BBD",
    "currencyname":"Dollar",
    "phone":"+1-246",
    "postal code format":"BB#####",
    "postal code regex":"^(?:BB)*(\\d{5})$",
    "languages":"en-BB"
  },
  {
    "iso":"BY",
    "country":"Belarus",
    "capital":"Minsk",
    "tld":".by",
    "currencycode":"BYR",
    "currencyname":"Ruble",
    "phone":"375",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"be,ru"
  },
  {
    "iso":"BE",
    "country":"Belgium",
    "capital":"Brussels",
    "tld":".be",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"32",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"nl-BE,fr-BE,de-BE"
  },
  {
    "iso":"BZ",
    "country":"Belize",
    "capital":"Belmopan",
    "tld":".bz",
    "currencycode":"BZD",
    "currencyname":"Dollar",
    "phone":"501",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-BZ,es"
  },
  {
    "iso":"BJ",
    "country":"Benin",
    "capital":"Porto-Novo",
    "tld":".bj",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"229",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-BJ"
  },
  {
    "iso":"BM",
    "country":"Bermuda",
    "capital":"Hamilton",
    "tld":".bm",
    "currencycode":"BMD",
    "currencyname":"Dollar",
    "phone":"+1-441",
    "postal code format":"@@ ##",
    "postal code regex":"^([A-Z]{2}\\d{2})$",
    "languages":"en-BM,pt"
  },
  {
    "iso":"BT",
    "country":"Bhutan",
    "capital":"Thimphu",
    "tld":".bt",
    "currencycode":"BTN",
    "currencyname":"Ngultrum",
    "phone":"975",
    "postal code format":"",
    "postal code regex":"",
    "languages":"dz"
  },
  {
    "iso":"BO",
    "country":"Bolivia",
    "capital":"Sucre",
    "tld":".bo",
    "currencycode":"BOB",
    "currencyname":"Boliviano",
    "phone":"591",
    "postal code format":"",
    "postal code regex":"",
    "languages":"es-BO,qu,ay"
  },
  {
    "iso":"BQ",
    "country":"Bonaire, Saint Eustatius and Saba ",
    "capital":"",
    "tld":".bq",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"599",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl,pap,en"
  },
  {
    "iso":"BA",
    "country":"Bosnia and Herzegovina",
    "capital":"Sarajevo",
    "tld":".ba",
    "currencycode":"BAM",
    "currencyname":"Marka",
    "phone":"387",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"bs,hr-BA,sr-BA"
  },
  {
    "iso":"BW",
    "country":"Botswana",
    "capital":"Gaborone",
    "tld":".bw",
    "currencycode":"BWP",
    "currencyname":"Pula",
    "phone":"267",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-BW,tn-BW"
  },
  {
    "iso":"BV",
    "country":"Bouvet Island",
    "capital":"",
    "tld":".bv",
    "currencycode":"NOK",
    "currencyname":"Krone",
    "phone":"",
    "postal code format":"",
    "postal code regex":"",
    "languages":""
  },
  {
    "iso":"BR",
    "country":"Brazil",
    "capital":"Brasilia",
    "tld":".br",
    "currencycode":"BRL",
    "currencyname":"Real",
    "phone":"55",
    "postal code format":"#####-###",
    "postal code regex":"^(\\d{8})$",
    "languages":"pt-BR,es,en,fr"
  },
  {
    "iso":"IO",
    "country":"British Indian Ocean Territory",
    "capital":"Diego Garcia",
    "tld":".io",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"246",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-IO"
  },
  {
    "iso":"VG",
    "country":"British Virgin Islands",
    "capital":"Road Town",
    "tld":".vg",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-284",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-VG"
  },
  {
    "iso":"BN",
    "country":"Brunei",
    "capital":"Bandar Seri Begawan",
    "tld":".bn",
    "currencycode":"BND",
    "currencyname":"Dollar",
    "phone":"673",
    "postal code format":"@@####",
    "postal code regex":"^([A-Z]{2}\\d{4})$",
    "languages":"ms-BN,en-BN"
  },
  {
    "iso":"BG",
    "country":"Bulgaria",
    "capital":"Sofia",
    "tld":".bg",
    "currencycode":"BGN",
    "currencyname":"Lev",
    "phone":"359",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"bg,tr-BG"
  },
  {
    "iso":"BF",
    "country":"Burkina Faso",
    "capital":"Ouagadougou",
    "tld":".bf",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"226",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-BF"
  },
  {
    "iso":"BI",
    "country":"Burundi",
    "capital":"Bujumbura",
    "tld":".bi",
    "currencycode":"BIF",
    "currencyname":"Franc",
    "phone":"257",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-BI,rn"
  },
  {
    "iso":"KH",
    "country":"Cambodia",
    "capital":"Phnom Penh",
    "tld":".kh",
    "currencycode":"KHR",
    "currencyname":"Riels",
    "phone":"855",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"km,fr,en"
  },
  {
    "iso":"CM",
    "country":"Cameroon",
    "capital":"Yaounde",
    "tld":".cm",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"237",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-CM,fr-CM"
  },
  {
    "iso":"CA",
    "country":"Canada",
    "capital":"Ottawa",
    "tld":".ca",
    "currencycode":"CAD",
    "currencyname":"Dollar",
    "phone":"1",
    "postal code format":"@#@ #@#",
    "postal code regex":"^([ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\\d[ABCEGHJKLMNPRSTVWXYZ]\\d)$ ",
    "languages":"en-CA,fr-CA,iu"
  },
  {
    "iso":"CV",
    "country":"Cape Verde",
    "capital":"Praia",
    "tld":".cv",
    "currencycode":"CVE",
    "currencyname":"Escudo",
    "phone":"238",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"pt-CV"
  },
  {
    "iso":"KY",
    "country":"Cayman Islands",
    "capital":"George Town",
    "tld":".ky",
    "currencycode":"KYD",
    "currencyname":"Dollar",
    "phone":"+1-345",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-KY"
  },
  {
    "iso":"CF",
    "country":"Central African Republic",
    "capital":"Bangui",
    "tld":".cf",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"236",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-CF,sg,ln,kg"
  },
  {
    "iso":"TD",
    "country":"Chad",
    "capital":"N'Djamena",
    "tld":".td",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"235",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-TD,ar-TD,sre"
  },
  {
    "iso":"CL",
    "country":"Chile",
    "capital":"Santiago",
    "tld":".cl",
    "currencycode":"CLP",
    "currencyname":"Peso",
    "phone":"56",
    "postal code format":"#######",
    "postal code regex":"^(\\d{7})$",
    "languages":"es-CL"
  },
  {
    "iso":"CN",
    "country":"China",
    "capital":"Beijing",
    "tld":".cn",
    "currencycode":"CNY",
    "currencyname":"Yuan Renminbi",
    "phone":"86",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"zh-CN,yue,wuu,dta,ug,za"
  },
  {
    "iso":"CX",
    "country":"Christmas Island",
    "capital":"Flying Fish Cove",
    "tld":".cx",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"61",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"en,zh,ms-CC"
  },
  {
    "iso":"CC",
    "country":"Cocos Islands",
    "capital":"West Island",
    "tld":".cc",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"61",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ms-CC,en"
  },
  {
    "iso":"CO",
    "country":"Colombia",
    "capital":"Bogota",
    "tld":".co",
    "currencycode":"COP",
    "currencyname":"Peso",
    "phone":"57",
    "postal code format":"",
    "postal code regex":"",
    "languages":"es-CO"
  },
  {
    "iso":"KM",
    "country":"Comoros",
    "capital":"Moroni",
    "tld":".km",
    "currencycode":"KMF",
    "currencyname":"Franc",
    "phone":"269",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar,fr-KM"
  },
  {
    "iso":"CK",
    "country":"Cook Islands",
    "capital":"Avarua",
    "tld":".ck",
    "currencycode":"NZD",
    "currencyname":"Dollar",
    "phone":"682",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-CK,mi"
  },
  {
    "iso":"CR",
    "country":"Costa Rica",
    "capital":"San Jose",
    "tld":".cr",
    "currencycode":"CRC",
    "currencyname":"Colon",
    "phone":"506",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"es-CR,en"
  },
  {
    "iso":"HR",
    "country":"Croatia",
    "capital":"Zagreb",
    "tld":".hr",
    "currencycode":"HRK",
    "currencyname":"Kuna",
    "phone":"385",
    "postal code format":"#####",
    "postal code regex":"^(?:HR)*(\\d{5})$",
    "languages":"hr-HR,sr"
  },
  {
    "iso":"CU",
    "country":"Cuba",
    "capital":"Havana",
    "tld":".cu",
    "currencycode":"CUP",
    "currencyname":"Peso",
    "phone":"53",
    "postal code format":"CP #####",
    "postal code regex":"^(?:CP)*(\\d{5})$",
    "languages":"es-CU"
  },
  {
    "iso":"CW",
    "country":"Curacao",
    "capital":" Willemstad",
    "tld":".cw",
    "currencycode":"ANG",
    "currencyname":"Guilder",
    "phone":"599",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl,pap"
  },
  {
    "iso":"CY",
    "country":"Cyprus",
    "capital":"Nicosia",
    "tld":".cy",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"357",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"el-CY,tr-CY,en"
  },
  {
    "iso":"CZ",
    "country":"Czech Republic",
    "capital":"Prague",
    "tld":".cz",
    "currencycode":"CZK",
    "currencyname":"Koruna",
    "phone":"420",
    "postal code format":"### ##",
    "postal code regex":"^(\\d{5})$",
    "languages":"cs,sk"
  },
  {
    "iso":"CD",
    "country":"Democratic Republic of the Congo",
    "capital":"Kinshasa",
    "tld":".cd",
    "currencycode":"CDF",
    "currencyname":"Franc",
    "phone":"243",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-CD,ln,kg"
  },
  {
    "iso":"DK",
    "country":"Denmark",
    "capital":"Copenhagen",
    "tld":".dk",
    "currencycode":"DKK",
    "currencyname":"Krone",
    "phone":"45",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"da-DK,en,fo,de-DK"
  },
  {
    "iso":"DJ",
    "country":"Djibouti",
    "capital":"Djibouti",
    "tld":".dj",
    "currencycode":"DJF",
    "currencyname":"Franc",
    "phone":"253",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-DJ,ar,so-DJ,aa"
  },
  {
    "iso":"DM",
    "country":"Dominica",
    "capital":"Roseau",
    "tld":".dm",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-767",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-DM"
  },
  {
    "iso":"DO",
    "country":"Dominican Republic",
    "capital":"Santo Domingo",
    "tld":".do",
    "currencycode":"DOP",
    "currencyname":"Peso",
    "phone":"+1-809 and 1-829",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"es-DO"
  },
  {
    "iso":"TL",
    "country":"East Timor",
    "capital":"Dili",
    "tld":".tl",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"670",
    "postal code format":"",
    "postal code regex":"",
    "languages":"tet,pt-TL,id,en"
  },
  {
    "iso":"EC",
    "country":"Ecuador",
    "capital":"Quito",
    "tld":".ec",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"593",
    "postal code format":"@####@",
    "postal code regex":"^([a-zA-Z]\\d{4}[a-zA-Z])$",
    "languages":"es-EC"
  },
  {
    "iso":"EG",
    "country":"Egypt",
    "capital":"Cairo",
    "tld":".eg",
    "currencycode":"EGP",
    "currencyname":"Pound",
    "phone":"20",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-EG,en,fr"
  },
  {
    "iso":"SV",
    "country":"El Salvador",
    "capital":"San Salvador",
    "tld":".sv",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"503",
    "postal code format":"CP ####",
    "postal code regex":"^(?:CP)*(\\d{4})$",
    "languages":"es-SV"
  },
  {
    "iso":"GQ",
    "country":"Equatorial Guinea",
    "capital":"Malabo",
    "tld":".gq",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"240",
    "postal code format":"",
    "postal code regex":"",
    "languages":"es-GQ,fr"
  },
  {
    "iso":"ER",
    "country":"Eritrea",
    "capital":"Asmara",
    "tld":".er",
    "currencycode":"ERN",
    "currencyname":"Nakfa",
    "phone":"291",
    "postal code format":"",
    "postal code regex":"",
    "languages":"aa-ER,ar,tig,kun,ti-ER"
  },
  {
    "iso":"EE",
    "country":"Estonia",
    "capital":"Tallinn",
    "tld":".ee",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"372",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"et,ru"
  },
  {
    "iso":"ET",
    "country":"Ethiopia",
    "capital":"Addis Ababa",
    "tld":".et",
    "currencycode":"ETB",
    "currencyname":"Birr",
    "phone":"251",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"am,en-ET,om-ET,ti-ET,so-ET,sid"
  },
  {
    "iso":"FK",
    "country":"Falkland Islands",
    "capital":"Stanley",
    "tld":".fk",
    "currencycode":"FKP",
    "currencyname":"Pound",
    "phone":"500",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-FK"
  },
  {
    "iso":"FO",
    "country":"Faroe Islands",
    "capital":"Torshavn",
    "tld":".fo",
    "currencycode":"DKK",
    "currencyname":"Krone",
    "phone":"298",
    "postal code format":"FO-###",
    "postal code regex":"^(?:FO)*(\\d{3})$",
    "languages":"fo,da-FO"
  },
  {
    "iso":"FJ",
    "country":"Fiji",
    "capital":"Suva",
    "tld":".fj",
    "currencycode":"FJD",
    "currencyname":"Dollar",
    "phone":"679",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-FJ,fj"
  },
  {
    "iso":"FI",
    "country":"Finland",
    "capital":"Helsinki",
    "tld":".fi",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"358",
    "postal code format":"#####",
    "postal code regex":"^(?:FI)*(\\d{5})$",
    "languages":"fi-FI,sv-FI,smn"
  },
  {
    "iso":"FR",
    "country":"France",
    "capital":"Paris",
    "tld":".fr",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"33",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-FR,frp,br,co,ca,eu,oc"
  },
  {
    "iso":"GF",
    "country":"French Guiana",
    "capital":"Cayenne",
    "tld":".gf",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"594",
    "postal code format":"#####",
    "postal code regex":"^((97|98)3\\d{2})$",
    "languages":"fr-GF"
  },
  {
    "iso":"PF",
    "country":"French Polynesia",
    "capital":"Papeete",
    "tld":".pf",
    "currencycode":"XPF",
    "currencyname":"Franc",
    "phone":"689",
    "postal code format":"#####",
    "postal code regex":"^((97|98)7\\d{2})$",
    "languages":"fr-PF,ty"
  },
  {
    "iso":"TF",
    "country":"French Southern Territories",
    "capital":"Port-aux-Francais",
    "tld":".tf",
    "currencycode":"EUR",
    "currencyname":"Euro  ",
    "phone":"",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr"
  },
  {
    "iso":"GA",
    "country":"Gabon",
    "capital":"Libreville",
    "tld":".ga",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"241",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-GA"
  },
  {
    "iso":"GM",
    "country":"Gambia",
    "capital":"Banjul",
    "tld":".gm",
    "currencycode":"GMD",
    "currencyname":"Dalasi",
    "phone":"220",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-GM,mnk,wof,wo,ff"
  },
  {
    "iso":"GE",
    "country":"Georgia",
    "capital":"Tbilisi",
    "tld":".ge",
    "currencycode":"GEL",
    "currencyname":"Lari",
    "phone":"995",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"ka,ru,hy,az"
  },
  {
    "iso":"DE",
    "country":"Germany",
    "capital":"Berlin",
    "tld":".de",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"49",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"de"
  },
  {
    "iso":"GH",
    "country":"Ghana",
    "capital":"Accra",
    "tld":".gh",
    "currencycode":"GHS",
    "currencyname":"Cedi",
    "phone":"233",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-GH,ak,ee,tw"
  },
  {
    "iso":"GI",
    "country":"Gibraltar",
    "capital":"Gibraltar",
    "tld":".gi",
    "currencycode":"GIP",
    "currencyname":"Pound",
    "phone":"350",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-GI,es,it,pt"
  },
  {
    "iso":"GR",
    "country":"Greece",
    "capital":"Athens",
    "tld":".gr",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"30",
    "postal code format":"### ##",
    "postal code regex":"^(\\d{5})$",
    "languages":"el-GR,en,fr"
  },
  {
    "iso":"GL",
    "country":"Greenland",
    "capital":"Nuuk",
    "tld":".gl",
    "currencycode":"DKK",
    "currencyname":"Krone",
    "phone":"299",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"kl,da-GL,en"
  },
  {
    "iso":"GD",
    "country":"Grenada",
    "capital":"St. George's",
    "tld":".gd",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-473",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-GD"
  },
  {
    "iso":"GP",
    "country":"Guadeloupe",
    "capital":"Basse-Terre",
    "tld":".gp",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"590",
    "postal code format":"#####",
    "postal code regex":"^((97|98)\\d{3})$",
    "languages":"fr-GP"
  },
  {
    "iso":"GU",
    "country":"Guam",
    "capital":"Hagatna",
    "tld":".gu",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-671",
    "postal code format":"969##",
    "postal code regex":"^(969\\d{2})$",
    "languages":"en-GU,ch-GU"
  },
  {
    "iso":"GT",
    "country":"Guatemala",
    "capital":"Guatemala City",
    "tld":".gt",
    "currencycode":"GTQ",
    "currencyname":"Quetzal",
    "phone":"502",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"es-GT"
  },
  {
    "iso":"GG",
    "country":"Guernsey",
    "capital":"St Peter Port",
    "tld":".gg",
    "currencycode":"GBP",
    "currencyname":"Pound",
    "phone":"+44-1481",
    "postal code format":"@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    "postal code regex":"^(([A-Z]\\d{2}[A-Z]{2})|([A-Z]\\d{3}[A-Z]{2})|([A-Z]{2}\\d{2}[A-Z]{2})|([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]\\d[A-Z]\\d[A-Z]{2})|([A-Z]{2}\\d[A-Z]\\d[A-Z]{2})|(GIR0AA))$",
    "languages":"en,fr"
  },
  {
    "iso":"GN",
    "country":"Guinea",
    "capital":"Conakry",
    "tld":".gn",
    "currencycode":"GNF",
    "currencyname":"Franc",
    "phone":"224",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-GN"
  },
  {
    "iso":"GW",
    "country":"Guinea-Bissau",
    "capital":"Bissau",
    "tld":".gw",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"245",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"pt-GW,pov"
  },
  {
    "iso":"GY",
    "country":"Guyana",
    "capital":"Georgetown",
    "tld":".gy",
    "currencycode":"GYD",
    "currencyname":"Dollar",
    "phone":"592",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-GY"
  },
  {
    "iso":"HT",
    "country":"Haiti",
    "capital":"Port-au-Prince",
    "tld":".ht",
    "currencycode":"HTG",
    "currencyname":"Gourde",
    "phone":"509",
    "postal code format":"HT####",
    "postal code regex":"^(?:HT)*(\\d{4})$",
    "languages":"ht,fr-HT"
  },
  {
    "iso":"HM",
    "country":"Heard Island and McDonald Islands",
    "capital":"",
    "tld":".hm",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":" ",
    "postal code format":"",
    "postal code regex":"",
    "languages":""
  },
  {
    "iso":"HN",
    "country":"Honduras",
    "capital":"Tegucigalpa",
    "tld":".hn",
    "currencycode":"HNL",
    "currencyname":"Lempira",
    "phone":"504",
    "postal code format":"@@####",
    "postal code regex":"^([A-Z]{2}\\d{4})$",
    "languages":"es-HN"
  },
  {
    "iso":"HK",
    "country":"Hong Kong",
    "capital":"Hong Kong",
    "tld":".hk",
    "currencycode":"HKD",
    "currencyname":"Dollar",
    "phone":"852",
    "postal code format":"",
    "postal code regex":"",
    "languages":"zh-HK,yue,zh,en"
  },
  {
    "iso":"HU",
    "country":"Hungary",
    "capital":"Budapest",
    "tld":".hu",
    "currencycode":"HUF",
    "currencyname":"Forint",
    "phone":"36",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"hu-HU"
  },
  {
    "iso":"IS",
    "country":"Iceland",
    "capital":"Reykjavik",
    "tld":".is",
    "currencycode":"ISK",
    "currencyname":"Krona",
    "phone":"354",
    "postal code format":"###",
    "postal code regex":"^(\\d{3})$",
    "languages":"is,en,de,da,sv,no"
  },
  {
    "iso":"IN",
    "country":"India",
    "capital":"New Delhi",
    "tld":".in",
    "currencycode":"INR",
    "currencyname":"Rupee",
    "phone":"91",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc"
  },
  {
    "iso":"ID",
    "country":"Indonesia",
    "capital":"Jakarta",
    "tld":".id",
    "currencycode":"IDR",
    "currencyname":"Rupiah",
    "phone":"62",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"id,en,nl,jv"
  },
  {
    "iso":"IR",
    "country":"Iran",
    "capital":"Tehran",
    "tld":".ir",
    "currencycode":"IRR",
    "currencyname":"Rial",
    "phone":"98",
    "postal code format":"##########",
    "postal code regex":"^(\\d{10})$",
    "languages":"fa-IR,ku"
  },
  {
    "iso":"IQ",
    "country":"Iraq",
    "capital":"Baghdad",
    "tld":".iq",
    "currencycode":"IQD",
    "currencyname":"Dinar",
    "phone":"964",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-IQ,ku,hy"
  },
  {
    "iso":"IE",
    "country":"Ireland",
    "capital":"Dublin",
    "tld":".ie",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"353",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-IE,ga-IE"
  },
  {
    "iso":"IM",
    "country":"Isle of Man",
    "capital":"Douglas, Isle of Man",
    "tld":".im",
    "currencycode":"GBP",
    "currencyname":"Pound",
    "phone":"+44-1624",
    "postal code format":"@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    "postal code regex":"^(([A-Z]\\d{2}[A-Z]{2})|([A-Z]\\d{3}[A-Z]{2})|([A-Z]{2}\\d{2}[A-Z]{2})|([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]\\d[A-Z]\\d[A-Z]{2})|([A-Z]{2}\\d[A-Z]\\d[A-Z]{2})|(GIR0AA))$",
    "languages":"en,gv"
  },
  {
    "iso":"IL",
    "country":"Israel",
    "capital":"Jerusalem",
    "tld":".il",
    "currencycode":"ILS",
    "currencyname":"Shekel",
    "phone":"972",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"he,ar-IL,en-IL,"
  },
  {
    "iso":"IT",
    "country":"Italy",
    "capital":"Rome",
    "tld":".it",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"39",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"it-IT,de-IT,fr-IT,sc,ca,co,sl"
  },
  {
    "iso":"CI",
    "country":"Ivory Coast",
    "capital":"Yamoussoukro",
    "tld":".ci",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"225",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-CI"
  },
  {
    "iso":"JM",
    "country":"Jamaica",
    "capital":"Kingston",
    "tld":".jm",
    "currencycode":"JMD",
    "currencyname":"Dollar",
    "phone":"+1-876",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-JM"
  },
  {
    "iso":"JP",
    "country":"Japan",
    "capital":"Tokyo",
    "tld":".jp",
    "currencycode":"JPY",
    "currencyname":"Yen",
    "phone":"81",
    "postal code format":"###-####",
    "postal code regex":"^(\\d{7})$",
    "languages":"ja"
  },
  {
    "iso":"JE",
    "country":"Jersey",
    "capital":"Saint Helier",
    "tld":".je",
    "currencycode":"GBP",
    "currencyname":"Pound",
    "phone":"+44-1534",
    "postal code format":"@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    "postal code regex":"^(([A-Z]\\d{2}[A-Z]{2})|([A-Z]\\d{3}[A-Z]{2})|([A-Z]{2}\\d{2}[A-Z]{2})|([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]\\d[A-Z]\\d[A-Z]{2})|([A-Z]{2}\\d[A-Z]\\d[A-Z]{2})|(GIR0AA))$",
    "languages":"en,pt"
  },
  {
    "iso":"JO",
    "country":"Jordan",
    "capital":"Amman",
    "tld":".jo",
    "currencycode":"JOD",
    "currencyname":"Dinar",
    "phone":"962",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-JO,en"
  },
  {
    "iso":"KZ",
    "country":"Kazakhstan",
    "capital":"Astana",
    "tld":".kz",
    "currencycode":"KZT",
    "currencyname":"Tenge",
    "phone":"7",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"kk,ru"
  },
  {
    "iso":"KE",
    "country":"Kenya",
    "capital":"Nairobi",
    "tld":".ke",
    "currencycode":"KES",
    "currencyname":"Shilling",
    "phone":"254",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"en-KE,sw-KE"
  },
  {
    "iso":"KI",
    "country":"Kiribati",
    "capital":"Tarawa",
    "tld":".ki",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"686",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-KI,gil"
  },
  {
    "iso":"XK",
    "country":"Kosovo",
    "capital":"Pristina",
    "tld":"",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"",
    "postal code format":"",
    "postal code regex":"",
    "languages":"sq,sr"
  },
  {
    "iso":"KW",
    "country":"Kuwait",
    "capital":"Kuwait City",
    "tld":".kw",
    "currencycode":"KWD",
    "currencyname":"Dinar",
    "phone":"965",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-KW,en"
  },
  {
    "iso":"KG",
    "country":"Kyrgyzstan",
    "capital":"Bishkek",
    "tld":".kg",
    "currencycode":"KGS",
    "currencyname":"Som",
    "phone":"996",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"ky,uz,ru"
  },
  {
    "iso":"LA",
    "country":"Laos",
    "capital":"Vientiane",
    "tld":".la",
    "currencycode":"LAK",
    "currencyname":"Kip",
    "phone":"856",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"lo,fr,en"
  },
  {
    "iso":"LV",
    "country":"Latvia",
    "capital":"Riga",
    "tld":".lv",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"371",
    "postal code format":"LV-####",
    "postal code regex":"^(?:LV)*(\\d{4})$",
    "languages":"lv,ru,lt"
  },
  {
    "iso":"LB",
    "country":"Lebanon",
    "capital":"Beirut",
    "tld":".lb",
    "currencycode":"LBP",
    "currencyname":"Pound",
    "phone":"961",
    "postal code format":"#### ####|####",
    "postal code regex":"^(\\d{4}(\\d{4})?)$",
    "languages":"ar-LB,fr-LB,en,hy"
  },
  {
    "iso":"LS",
    "country":"Lesotho",
    "capital":"Maseru",
    "tld":".ls",
    "currencycode":"LSL",
    "currencyname":"Loti",
    "phone":"266",
    "postal code format":"###",
    "postal code regex":"^(\\d{3})$",
    "languages":"en-LS,st,zu,xh"
  },
  {
    "iso":"LR",
    "country":"Liberia",
    "capital":"Monrovia",
    "tld":".lr",
    "currencycode":"LRD",
    "currencyname":"Dollar",
    "phone":"231",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"en-LR"
  },
  {
    "iso":"LY",
    "country":"Libya",
    "capital":"Tripolis",
    "tld":".ly",
    "currencycode":"LYD",
    "currencyname":"Dinar",
    "phone":"218",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-LY,it,en"
  },
  {
    "iso":"LI",
    "country":"Liechtenstein",
    "capital":"Vaduz",
    "tld":".li",
    "currencycode":"CHF",
    "currencyname":"Franc",
    "phone":"423",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"de-LI"
  },
  {
    "iso":"LT",
    "country":"Lithuania",
    "capital":"Vilnius",
    "tld":".lt",
    "currencycode":"LTL",
    "currencyname":"Litas",
    "phone":"370",
    "postal code format":"LT-#####",
    "postal code regex":"^(?:LT)*(\\d{5})$",
    "languages":"lt,ru,pl"
  },
  {
    "iso":"LU",
    "country":"Luxembourg",
    "capital":"Luxembourg",
    "tld":".lu",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"352",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"lb,de-LU,fr-LU"
  },
  {
    "iso":"MO",
    "country":"Macao",
    "capital":"Macao",
    "tld":".mo",
    "currencycode":"MOP",
    "currencyname":"Pataca",
    "phone":"853",
    "postal code format":"",
    "postal code regex":"",
    "languages":"zh,zh-MO,pt"
  },
  {
    "iso":"MK",
    "country":"Macedonia",
    "capital":"Skopje",
    "tld":".mk",
    "currencycode":"MKD",
    "currencyname":"Denar",
    "phone":"389",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"mk,sq,tr,rmm,sr"
  },
  {
    "iso":"MG",
    "country":"Madagascar",
    "capital":"Antananarivo",
    "tld":".mg",
    "currencycode":"MGA",
    "currencyname":"Ariary",
    "phone":"261",
    "postal code format":"###",
    "postal code regex":"^(\\d{3})$",
    "languages":"fr-MG,mg"
  },
  {
    "iso":"MW",
    "country":"Malawi",
    "capital":"Lilongwe",
    "tld":".mw",
    "currencycode":"MWK",
    "currencyname":"Kwacha",
    "phone":"265",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ny,yao,tum,swk"
  },
  {
    "iso":"MY",
    "country":"Malaysia",
    "capital":"Kuala Lumpur",
    "tld":".my",
    "currencycode":"MYR",
    "currencyname":"Ringgit",
    "phone":"60",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ms-MY,en,zh,ta,te,ml,pa,th"
  },
  {
    "iso":"MV",
    "country":"Maldives",
    "capital":"Male",
    "tld":".mv",
    "currencycode":"MVR",
    "currencyname":"Rufiyaa",
    "phone":"960",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"dv,en"
  },
  {
    "iso":"ML",
    "country":"Mali",
    "capital":"Bamako",
    "tld":".ml",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"223",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-ML,bm"
  },
  {
    "iso":"MT",
    "country":"Malta",
    "capital":"Valletta",
    "tld":".mt",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"356",
    "postal code format":"@@@ ###|@@@ ##",
    "postal code regex":"^([A-Z]{3}\\d{2}\\d?)$",
    "languages":"mt,en-MT"
  },
  {
    "iso":"MH",
    "country":"Marshall Islands",
    "capital":"Majuro",
    "tld":".mh",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"692",
    "postal code format":"",
    "postal code regex":"",
    "languages":"mh,en-MH"
  },
  {
    "iso":"MQ",
    "country":"Martinique",
    "capital":"Fort-de-France",
    "tld":".mq",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"596",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-MQ"
  },
  {
    "iso":"MR",
    "country":"Mauritania",
    "capital":"Nouakchott",
    "tld":".mr",
    "currencycode":"MRO",
    "currencyname":"Ouguiya",
    "phone":"222",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-MR,fuc,snk,fr,mey,wo"
  },
  {
    "iso":"MU",
    "country":"Mauritius",
    "capital":"Port Louis",
    "tld":".mu",
    "currencycode":"MUR",
    "currencyname":"Rupee",
    "phone":"230",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-MU,bho,fr"
  },
  {
    "iso":"YT",
    "country":"Mayotte",
    "capital":"Mamoudzou",
    "tld":".yt",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"262",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-YT"
  },
  {
    "iso":"MX",
    "country":"Mexico",
    "capital":"Mexico City",
    "tld":".mx",
    "currencycode":"MXN",
    "currencyname":"Peso",
    "phone":"52",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"es-MX"
  },
  {
    "iso":"FM",
    "country":"Micronesia",
    "capital":"Palikir",
    "tld":".fm",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"691",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg"
  },
  {
    "iso":"MD",
    "country":"Moldova",
    "capital":"Chisinau",
    "tld":".md",
    "currencycode":"MDL",
    "currencyname":"Leu",
    "phone":"373",
    "postal code format":"MD-####",
    "postal code regex":"^(?:MD)*(\\d{4})$",
    "languages":"ro,ru,gag,tr"
  },
  {
    "iso":"MC",
    "country":"Monaco",
    "capital":"Monaco",
    "tld":".mc",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"377",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-MC,en,it"
  },
  {
    "iso":"MN",
    "country":"Mongolia",
    "capital":"Ulan Bator",
    "tld":".mn",
    "currencycode":"MNT",
    "currencyname":"Tugrik",
    "phone":"976",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"mn,ru"
  },
  {
    "iso":"ME",
    "country":"Montenegro",
    "capital":"Podgorica",
    "tld":".me",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"382",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"sr,hu,bs,sq,hr,rom"
  },
  {
    "iso":"MS",
    "country":"Montserrat",
    "capital":"Plymouth",
    "tld":".ms",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-664",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-MS"
  },
  {
    "iso":"MA",
    "country":"Morocco",
    "capital":"Rabat",
    "tld":".ma",
    "currencycode":"MAD",
    "currencyname":"Dirham",
    "phone":"212",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-MA,fr"
  },
  {
    "iso":"MZ",
    "country":"Mozambique",
    "capital":"Maputo",
    "tld":".mz",
    "currencycode":"MZN",
    "currencyname":"Metical",
    "phone":"258",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"pt-MZ,vmw"
  },
  {
    "iso":"MM",
    "country":"Myanmar",
    "capital":"Nay Pyi Taw",
    "tld":".mm",
    "currencycode":"MMK",
    "currencyname":"Kyat",
    "phone":"95",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"my"
  },
  {
    "iso":"NA",
    "country":"Namibia",
    "capital":"Windhoek",
    "tld":".na",
    "currencycode":"NAD",
    "currencyname":"Dollar",
    "phone":"264",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-NA,af,de,hz,naq"
  },
  {
    "iso":"NR",
    "country":"Nauru",
    "capital":"Yaren",
    "tld":".nr",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"674",
    "postal code format":"",
    "postal code regex":"",
    "languages":"na,en-NR"
  },
  {
    "iso":"NP",
    "country":"Nepal",
    "capital":"Kathmandu",
    "tld":".np",
    "currencycode":"NPR",
    "currencyname":"Rupee",
    "phone":"977",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ne,en"
  },
  {
    "iso":"NL",
    "country":"Netherlands",
    "capital":"Amsterdam",
    "tld":".nl",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"31",
    "postal code format":"#### @@",
    "postal code regex":"^(\\d{4}[A-Z]{2})$",
    "languages":"nl-NL,fy-NL"
  },
  {
    "iso":"AN",
    "country":"Netherlands Antilles",
    "capital":"Willemstad",
    "tld":".an",
    "currencycode":"ANG",
    "currencyname":"Guilder",
    "phone":"599",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl-AN,en,es"
  },
  {
    "iso":"NC",
    "country":"New Caledonia",
    "capital":"Noumea",
    "tld":".nc",
    "currencycode":"XPF",
    "currencyname":"Franc",
    "phone":"687",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-NC"
  },
  {
    "iso":"NZ",
    "country":"New Zealand",
    "capital":"Wellington",
    "tld":".nz",
    "currencycode":"NZD",
    "currencyname":"Dollar",
    "phone":"64",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"en-NZ,mi"
  },
  {
    "iso":"NI",
    "country":"Nicaragua",
    "capital":"Managua",
    "tld":".ni",
    "currencycode":"NIO",
    "currencyname":"Cordoba",
    "phone":"505",
    "postal code format":"###-###-#",
    "postal code regex":"^(\\d{7})$",
    "languages":"es-NI,en"
  },
  {
    "iso":"NE",
    "country":"Niger",
    "capital":"Niamey",
    "tld":".ne",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"227",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"fr-NE,ha,kr,dje"
  },
  {
    "iso":"NG",
    "country":"Nigeria",
    "capital":"Abuja",
    "tld":".ng",
    "currencycode":"NGN",
    "currencyname":"Naira",
    "phone":"234",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"en-NG,ha,yo,ig,ff"
  },
  {
    "iso":"NU",
    "country":"Niue",
    "capital":"Alofi",
    "tld":".nu",
    "currencycode":"NZD",
    "currencyname":"Dollar",
    "phone":"683",
    "postal code format":"",
    "postal code regex":"",
    "languages":"niu,en-NU"
  },
  {
    "iso":"NF",
    "country":"Norfolk Island",
    "capital":"Kingston",
    "tld":".nf",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"672",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"en-NF"
  },
  {
    "iso":"KP",
    "country":"North Korea",
    "capital":"Pyongyang",
    "tld":".kp",
    "currencycode":"KPW",
    "currencyname":"Won",
    "phone":"850",
    "postal code format":"###-###",
    "postal code regex":"^(\\d{6})$",
    "languages":"ko-KP"
  },
  {
    "iso":"MP",
    "country":"Northern Mariana Islands",
    "capital":"Saipan",
    "tld":".mp",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-670",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fil,tl,zh,ch-MP,en-MP"
  },
  {
    "iso":"NO",
    "country":"Norway",
    "capital":"Oslo",
    "tld":".no",
    "currencycode":"NOK",
    "currencyname":"Krone",
    "phone":"47",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"no,nb,nn,se,fi"
  },
  {
    "iso":"OM",
    "country":"Oman",
    "capital":"Muscat",
    "tld":".om",
    "currencycode":"OMR",
    "currencyname":"Rial",
    "phone":"968",
    "postal code format":"###",
    "postal code regex":"^(\\d{3})$",
    "languages":"ar-OM,en,bal,ur"
  },
  {
    "iso":"PK",
    "country":"Pakistan",
    "capital":"Islamabad",
    "tld":".pk",
    "currencycode":"PKR",
    "currencyname":"Rupee",
    "phone":"92",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ur-PK,en-PK,pa,sd,ps,brh"
  },
  {
    "iso":"PW",
    "country":"Palau",
    "capital":"Melekeok",
    "tld":".pw",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"680",
    "postal code format":"96940",
    "postal code regex":"^(96940)$",
    "languages":"pau,sov,en-PW,tox,ja,fil,zh"
  },
  {
    "iso":"PS",
    "country":"Palestinian Territory",
    "capital":"East Jerusalem",
    "tld":".ps",
    "currencycode":"ILS",
    "currencyname":"Shekel",
    "phone":"970",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-PS"
  },
  {
    "iso":"PA",
    "country":"Panama",
    "capital":"Panama City",
    "tld":".pa",
    "currencycode":"PAB",
    "currencyname":"Balboa",
    "phone":"507",
    "postal code format":"",
    "postal code regex":"",
    "languages":"es-PA,en"
  },
  {
    "iso":"PG",
    "country":"Papua New Guinea",
    "capital":"Port Moresby",
    "tld":".pg",
    "currencycode":"PGK",
    "currencyname":"Kina",
    "phone":"675",
    "postal code format":"###",
    "postal code regex":"^(\\d{3})$",
    "languages":"en-PG,ho,meu,tpi"
  },
  {
    "iso":"PY",
    "country":"Paraguay",
    "capital":"Asuncion",
    "tld":".py",
    "currencycode":"PYG",
    "currencyname":"Guarani",
    "phone":"595",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"es-PY,gn"
  },
  {
    "iso":"PE",
    "country":"Peru",
    "capital":"Lima",
    "tld":".pe",
    "currencycode":"PEN",
    "currencyname":"Sol",
    "phone":"51",
    "postal code format":"",
    "postal code regex":"",
    "languages":"es-PE,qu,ay"
  },
  {
    "iso":"PH",
    "country":"Philippines",
    "capital":"Manila",
    "tld":".ph",
    "currencycode":"PHP",
    "currencyname":"Peso",
    "phone":"63",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"tl,en-PH,fil"
  },
  {
    "iso":"PN",
    "country":"Pitcairn",
    "capital":"Adamstown",
    "tld":".pn",
    "currencycode":"NZD",
    "currencyname":"Dollar",
    "phone":"870",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-PN"
  },
  {
    "iso":"PL",
    "country":"Poland",
    "capital":"Warsaw",
    "tld":".pl",
    "currencycode":"PLN",
    "currencyname":"Zloty",
    "phone":"48",
    "postal code format":"##-###",
    "postal code regex":"^(\\d{5})$",
    "languages":"pl"
  },
  {
    "iso":"PT",
    "country":"Portugal",
    "capital":"Lisbon",
    "tld":".pt",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"351",
    "postal code format":"####-###",
    "postal code regex":"^(\\d{7})$",
    "languages":"pt-PT,mwl"
  },
  {
    "iso":"PR",
    "country":"Puerto Rico",
    "capital":"San Juan",
    "tld":".pr",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-787 and 1-939",
    "postal code format":"#####-####",
    "postal code regex":"^(\\d{9})$",
    "languages":"en-PR,es-PR"
  },
  {
    "iso":"QA",
    "country":"Qatar",
    "capital":"Doha",
    "tld":".qa",
    "currencycode":"QAR",
    "currencyname":"Rial",
    "phone":"974",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-QA,es"
  },
  {
    "iso":"CG",
    "country":"Republic of the Congo",
    "capital":"Brazzaville",
    "tld":".cg",
    "currencycode":"XAF",
    "currencyname":"Franc",
    "phone":"242",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-CG,kg,ln-CG"
  },
  {
    "iso":"RE",
    "country":"Reunion",
    "capital":"Saint-Denis",
    "tld":".re",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"262",
    "postal code format":"#####",
    "postal code regex":"^((97|98)(4|7|8)\\d{2})$",
    "languages":"fr-RE"
  },
  {
    "iso":"RO",
    "country":"Romania",
    "capital":"Bucharest",
    "tld":".ro",
    "currencycode":"RON",
    "currencyname":"Leu",
    "phone":"40",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"ro,hu,rom"
  },
  {
    "iso":"RU",
    "country":"Russia",
    "capital":"Moscow",
    "tld":".ru",
    "currencycode":"RUB",
    "currencyname":"Ruble",
    "phone":"7",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog"
  },
  {
    "iso":"RW",
    "country":"Rwanda",
    "capital":"Kigali",
    "tld":".rw",
    "currencycode":"RWF",
    "currencyname":"Franc",
    "phone":"250",
    "postal code format":"",
    "postal code regex":"",
    "languages":"rw,en-RW,fr-RW,sw"
  },
  {
    "iso":"BL",
    "country":"Saint Barthelemy",
    "capital":"Gustavia",
    "tld":".gp",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"590",
    "postal code format":"### ###",
    "postal code regex":"",
    "languages":"fr"
  },
  {
    "iso":"SH",
    "country":"Saint Helena",
    "capital":"Jamestown",
    "tld":".sh",
    "currencycode":"SHP",
    "currencyname":"Pound",
    "phone":"290",
    "postal code format":"STHL 1ZZ",
    "postal code regex":"^(STHL1ZZ)$",
    "languages":"en-SH"
  },
  {
    "iso":"KN",
    "country":"Saint Kitts and Nevis",
    "capital":"Basseterre",
    "tld":".kn",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-869",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-KN"
  },
  {
    "iso":"LC",
    "country":"Saint Lucia",
    "capital":"Castries",
    "tld":".lc",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-758",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-LC"
  },
  {
    "iso":"MF",
    "country":"Saint Martin",
    "capital":"Marigot",
    "tld":".gp",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"590",
    "postal code format":"### ###",
    "postal code regex":"",
    "languages":"fr"
  },
  {
    "iso":"PM",
    "country":"Saint Pierre and Miquelon",
    "capital":"Saint-Pierre",
    "tld":".pm",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"508",
    "postal code format":"#####",
    "postal code regex":"^(97500)$",
    "languages":"fr-PM"
  },
  {
    "iso":"VC",
    "country":"Saint Vincent and the Grenadines",
    "capital":"Kingstown",
    "tld":".vc",
    "currencycode":"XCD",
    "currencyname":"Dollar",
    "phone":"+1-784",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-VC,fr"
  },
  {
    "iso":"WS",
    "country":"Samoa",
    "capital":"Apia",
    "tld":".ws",
    "currencycode":"WST",
    "currencyname":"Tala",
    "phone":"685",
    "postal code format":"",
    "postal code regex":"",
    "languages":"sm,en-WS"
  },
  {
    "iso":"SM",
    "country":"San Marino",
    "capital":"San Marino",
    "tld":".sm",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"378",
    "postal code format":"4789#",
    "postal code regex":"^(4789\\d)$",
    "languages":"it-SM"
  },
  {
    "iso":"ST",
    "country":"Sao Tome and Principe",
    "capital":"Sao Tome",
    "tld":".st",
    "currencycode":"STD",
    "currencyname":"Dobra",
    "phone":"239",
    "postal code format":"",
    "postal code regex":"",
    "languages":"pt-ST"
  },
  {
    "iso":"SA",
    "country":"Saudi Arabia",
    "capital":"Riyadh",
    "tld":".sa",
    "currencycode":"SAR",
    "currencyname":"Rial",
    "phone":"966",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-SA"
  },
  {
    "iso":"SN",
    "country":"Senegal",
    "capital":"Dakar",
    "tld":".sn",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"221",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"fr-SN,wo,fuc,mnk"
  },
  {
    "iso":"RS",
    "country":"Serbia",
    "capital":"Belgrade",
    "tld":".rs",
    "currencycode":"RSD",
    "currencyname":"Dinar",
    "phone":"381",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"sr,hu,bs,rom"
  },
  {
    "iso":"CS",
    "country":"Serbia and Montenegro",
    "capital":"Belgrade",
    "tld":".cs",
    "currencycode":"RSD",
    "currencyname":"Dinar",
    "phone":"381",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"cu,hu,sq,sr"
  },
  {
    "iso":"SC",
    "country":"Seychelles",
    "capital":"Victoria",
    "tld":".sc",
    "currencycode":"SCR",
    "currencyname":"Rupee",
    "phone":"248",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-SC,fr-SC"
  },
  {
    "iso":"SL",
    "country":"Sierra Leone",
    "capital":"Freetown",
    "tld":".sl",
    "currencycode":"SLL",
    "currencyname":"Leone",
    "phone":"232",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-SL,men,tem"
  },
  {
    "iso":"SG",
    "country":"Singapore",
    "capital":"Singapur",
    "tld":".sg",
    "currencycode":"SGD",
    "currencyname":"Dollar",
    "phone":"65",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"cmn,en-SG,ms-SG,ta-SG,zh-SG"
  },
  {
    "iso":"SX",
    "country":"Sint Maarten",
    "capital":"Philipsburg",
    "tld":".sx",
    "currencycode":"ANG",
    "currencyname":"Guilder",
    "phone":"599",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl,en"
  },
  {
    "iso":"SK",
    "country":"Slovakia",
    "capital":"Bratislava",
    "tld":".sk",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"421",
    "postal code format":"### ##",
    "postal code regex":"^(\\d{5})$",
    "languages":"sk,hu"
  },
  {
    "iso":"SI",
    "country":"Slovenia",
    "capital":"Ljubljana",
    "tld":".si",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"386",
    "postal code format":"####",
    "postal code regex":"^(?:SI)*(\\d{4})$",
    "languages":"sl,sh"
  },
  {
    "iso":"SB",
    "country":"Solomon Islands",
    "capital":"Honiara",
    "tld":".sb",
    "currencycode":"SBD",
    "currencyname":"Dollar",
    "phone":"677",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-SB,tpi"
  },
  {
    "iso":"SO",
    "country":"Somalia",
    "capital":"Mogadishu",
    "tld":".so",
    "currencycode":"SOS",
    "currencyname":"Shilling",
    "phone":"252",
    "postal code format":"@@  #####",
    "postal code regex":"^([A-Z]{2}\\d{5})$",
    "languages":"so-SO,ar-SO,it,en-SO"
  },
  {
    "iso":"ZA",
    "country":"South Africa",
    "capital":"Pretoria",
    "tld":".za",
    "currencycode":"ZAR",
    "currencyname":"Rand",
    "phone":"27",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr"
  },
  {
    "iso":"GS",
    "country":"South Georgia and the South Sandwich Islands",
    "capital":"Grytviken",
    "tld":".gs",
    "currencycode":"GBP",
    "currencyname":"Pound",
    "phone":"",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en"
  },
  {
    "iso":"KR",
    "country":"South Korea",
    "capital":"Seoul",
    "tld":".kr",
    "currencycode":"KRW",
    "currencyname":"Won",
    "phone":"82",
    "postal code format":"SEOUL ###-###",
    "postal code regex":"^(?:SEOUL)*(\\d{6})$",
    "languages":"ko-KR,en"
  },
  {
    "iso":"SS",
    "country":"South Sudan",
    "capital":"Juba",
    "tld":"",
    "currencycode":"SSP",
    "currencyname":"Pound",
    "phone":"211",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en"
  },
  {
    "iso":"ES",
    "country":"Spain",
    "capital":"Madrid",
    "tld":".es",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"34",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"es-ES,ca,gl,eu,oc"
  },
  {
    "iso":"LK",
    "country":"Sri Lanka",
    "capital":"Colombo",
    "tld":".lk",
    "currencycode":"LKR",
    "currencyname":"Rupee",
    "phone":"94",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"si,ta,en"
  },
  {
    "iso":"SD",
    "country":"Sudan",
    "capital":"Khartoum",
    "tld":".sd",
    "currencycode":"SDG",
    "currencyname":"Pound",
    "phone":"249",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"ar-SD,en,fia"
  },
  {
    "iso":"SR",
    "country":"Suriname",
    "capital":"Paramaribo",
    "tld":".sr",
    "currencycode":"SRD",
    "currencyname":"Dollar",
    "phone":"597",
    "postal code format":"",
    "postal code regex":"",
    "languages":"nl-SR,en,srn,hns,jv"
  },
  {
    "iso":"SJ",
    "country":"Svalbard and Jan Mayen",
    "capital":"Longyearbyen",
    "tld":".sj",
    "currencycode":"NOK",
    "currencyname":"Krone",
    "phone":"47",
    "postal code format":"",
    "postal code regex":"",
    "languages":"no,ru"
  },
  {
    "iso":"SZ",
    "country":"Swaziland",
    "capital":"Mbabane",
    "tld":".sz",
    "currencycode":"SZL",
    "currencyname":"Lilangeni",
    "phone":"268",
    "postal code format":"@###",
    "postal code regex":"^([A-Z]\\d{3})$",
    "languages":"en-SZ,ss-SZ"
  },
  {
    "iso":"SE",
    "country":"Sweden",
    "capital":"Stockholm",
    "tld":".se",
    "currencycode":"SEK",
    "currencyname":"Krona",
    "phone":"46",
    "postal code format":"### ##",
    "postal code regex":"^(?:SE)*(\\d{5})$",
    "languages":"sv-SE,se,sma,fi-SE"
  },
  {
    "iso":"CH",
    "country":"Switzerland",
    "capital":"Berne",
    "tld":".ch",
    "currencycode":"CHF",
    "currencyname":"Franc",
    "phone":"41",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"de-CH,fr-CH,it-CH,rm"
  },
  {
    "iso":"SY",
    "country":"Syria",
    "capital":"Damascus",
    "tld":".sy",
    "currencycode":"SYP",
    "currencyname":"Pound",
    "phone":"963",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-SY,ku,hy,arc,fr,en"
  },
  {
    "iso":"TW",
    "country":"Taiwan",
    "capital":"Taipei",
    "tld":".tw",
    "currencycode":"TWD",
    "currencyname":"Dollar",
    "phone":"886",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"zh-TW,zh,nan,hak"
  },
  {
    "iso":"TJ",
    "country":"Tajikistan",
    "capital":"Dushanbe",
    "tld":".tj",
    "currencycode":"TJS",
    "currencyname":"Somoni",
    "phone":"992",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"tg,ru"
  },
  {
    "iso":"TZ",
    "country":"Tanzania",
    "capital":"Dodoma",
    "tld":".tz",
    "currencycode":"TZS",
    "currencyname":"Shilling",
    "phone":"255",
    "postal code format":"",
    "postal code regex":"",
    "languages":"sw-TZ,en,ar"
  },
  {
    "iso":"TH",
    "country":"Thailand",
    "capital":"Bangkok",
    "tld":".th",
    "currencycode":"THB",
    "currencyname":"Baht",
    "phone":"66",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"th,en"
  },
  {
    "iso":"TG",
    "country":"Togo",
    "capital":"Lome",
    "tld":".tg",
    "currencycode":"XOF",
    "currencyname":"Franc",
    "phone":"228",
    "postal code format":"",
    "postal code regex":"",
    "languages":"fr-TG,ee,hna,kbp,dag,ha"
  },
  {
    "iso":"TK",
    "country":"Tokelau",
    "capital":"",
    "tld":".tk",
    "currencycode":"NZD",
    "currencyname":"Dollar",
    "phone":"690",
    "postal code format":"",
    "postal code regex":"",
    "languages":"tkl,en-TK"
  },
  {
    "iso":"TO",
    "country":"Tonga",
    "capital":"Nuku'alofa",
    "tld":".to",
    "currencycode":"TOP",
    "currencyname":"Pa'anga",
    "phone":"676",
    "postal code format":"",
    "postal code regex":"",
    "languages":"to,en-TO"
  },
  {
    "iso":"TT",
    "country":"Trinidad and Tobago",
    "capital":"Port of Spain",
    "tld":".tt",
    "currencycode":"TTD",
    "currencyname":"Dollar",
    "phone":"+1-868",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-TT,hns,fr,es,zh"
  },
  {
    "iso":"TN",
    "country":"Tunisia",
    "capital":"Tunis",
    "tld":".tn",
    "currencycode":"TND",
    "currencyname":"Dinar",
    "phone":"216",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"ar-TN,fr"
  },
  {
    "iso":"TR",
    "country":"Turkey",
    "capital":"Ankara",
    "tld":".tr",
    "currencycode":"TRY",
    "currencyname":"Lira",
    "phone":"90",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"tr-TR,ku,diq,az,av"
  },
  {
    "iso":"TM",
    "country":"Turkmenistan",
    "capital":"Ashgabat",
    "tld":".tm",
    "currencycode":"TMT",
    "currencyname":"Manat",
    "phone":"993",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"tk,ru,uz"
  },
  {
    "iso":"TC",
    "country":"Turks and Caicos Islands",
    "capital":"Cockburn Town",
    "tld":".tc",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-649",
    "postal code format":"TKCA 1ZZ",
    "postal code regex":"^(TKCA 1ZZ)$",
    "languages":"en-TC"
  },
  {
    "iso":"TV",
    "country":"Tuvalu",
    "capital":"Funafuti",
    "tld":".tv",
    "currencycode":"AUD",
    "currencyname":"Dollar",
    "phone":"688",
    "postal code format":"",
    "postal code regex":"",
    "languages":"tvl,en,sm,gil"
  },
  {
    "iso":"VI",
    "country":"U.S. Virgin Islands",
    "capital":"Charlotte Amalie",
    "tld":".vi",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"+1-340",
    "postal code format":"#####-####",
    "postal code regex":"^\\d{5}(-\\d{4})?$",
    "languages":"en-VI"
  },
  {
    "iso":"UG",
    "country":"Uganda",
    "capital":"Kampala",
    "tld":".ug",
    "currencycode":"UGX",
    "currencyname":"Shilling",
    "phone":"256",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-UG,lg,sw,ar"
  },
  {
    "iso":"UA",
    "country":"Ukraine",
    "capital":"Kiev",
    "tld":".ua",
    "currencycode":"UAH",
    "currencyname":"Hryvnia",
    "phone":"380",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"uk,ru-UA,rom,pl,hu"
  },
  {
    "iso":"AE",
    "country":"United Arab Emirates",
    "capital":"Abu Dhabi",
    "tld":".ae",
    "currencycode":"AED",
    "currencyname":"Dirham",
    "phone":"971",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-AE,fa,en,hi,ur"
  },
  {
    "iso":"GB",
    "country":"United Kingdom",
    "capital":"London",
    "tld":".uk",
    "currencycode":"GBP",
    "currencyname":"Pound",
    "phone":"44",
    "postal code format":"@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    "postal code regex":"^(([A-Z]\\d{2}[A-Z]{2})|([A-Z]\\d{3}[A-Z]{2})|([A-Z]{2}\\d{2}[A-Z]{2})|([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]\\d[A-Z]\\d[A-Z]{2})|([A-Z]{2}\\d[A-Z]\\d[A-Z]{2})|(GIR0AA))$",
    "languages":"en-GB,cy-GB,gd"
  },
  {
    "iso":"US",
    "country":"United States",
    "capital":"Washington",
    "tld":".us",
    "currencycode":"USD",
    "currencyname":"Dollar",
    "phone":"1",
    "postal code format":"#####-####",
    "postal code regex":"^\\d{5}(-\\d{4})?$",
    "languages":"en-US,es-US,haw,fr"
  },
  {
    "iso":"UM",
    "country":"United States Minor Outlying Islands",
    "capital":"",
    "tld":".um",
    "currencycode":"USD",
    "currencyname":"Dollar ",
    "phone":"1",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-UM"
  },
  {
    "iso":"UY",
    "country":"Uruguay",
    "capital":"Montevideo",
    "tld":".uy",
    "currencycode":"UYU",
    "currencyname":"Peso",
    "phone":"598",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"es-UY"
  },
  {
    "iso":"UZ",
    "country":"Uzbekistan",
    "capital":"Tashkent",
    "tld":".uz",
    "currencycode":"UZS",
    "currencyname":"Som",
    "phone":"998",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"uz,ru,tg"
  },
  {
    "iso":"VU",
    "country":"Vanuatu",
    "capital":"Port Vila",
    "tld":".vu",
    "currencycode":"VUV",
    "currencyname":"Vatu",
    "phone":"678",
    "postal code format":"",
    "postal code regex":"",
    "languages":"bi,en-VU,fr-VU"
  },
  {
    "iso":"VA",
    "country":"Vatican",
    "capital":"Vatican City",
    "tld":".va",
    "currencycode":"EUR",
    "currencyname":"Euro",
    "phone":"379",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"la,it,fr"
  },
  {
    "iso":"VE",
    "country":"Venezuela",
    "capital":"Caracas",
    "tld":".ve",
    "currencycode":"VEF",
    "currencyname":"Bolivar",
    "phone":"58",
    "postal code format":"####",
    "postal code regex":"^(\\d{4})$",
    "languages":"es-VE"
  },
  {
    "iso":"VN",
    "country":"Vietnam",
    "capital":"Hanoi",
    "tld":".vn",
    "currencycode":"VND",
    "currencyname":"Dong",
    "phone":"84",
    "postal code format":"######",
    "postal code regex":"^(\\d{6})$",
    "languages":"vi,en,fr,zh,km"
  },
  {
    "iso":"WF",
    "country":"Wallis and Futuna",
    "capital":"Mata Utu",
    "tld":".wf",
    "currencycode":"XPF",
    "currencyname":"Franc",
    "phone":"681",
    "postal code format":"#####",
    "postal code regex":"^(986\\d{2})$",
    "languages":"wls,fud,fr-WF"
  },
  {
    "iso":"EH",
    "country":"Western Sahara",
    "capital":"El-Aaiun",
    "tld":".eh",
    "currencycode":"MAD",
    "currencyname":"Dirham",
    "phone":"212",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar,mey"
  },
  {
    "iso":"YE",
    "country":"Yemen",
    "capital":"Sanaa",
    "tld":".ye",
    "currencycode":"YER",
    "currencyname":"Rial",
    "phone":"967",
    "postal code format":"",
    "postal code regex":"",
    "languages":"ar-YE"
  },
  {
    "iso":"ZM",
    "country":"Zambia",
    "capital":"Lusaka",
    "tld":".zm",
    "currencycode":"ZMK",
    "currencyname":"Kwacha",
    "phone":"260",
    "postal code format":"#####",
    "postal code regex":"^(\\d{5})$",
    "languages":"en-ZM,bem,loz,lun,lue,ny,toi"
  },
  {
    "iso":"ZW",
    "country":"Zimbabwe",
    "capital":"Harare",
    "tld":".zw",
    "currencycode":"ZWL",
    "currencyname":"Dollar",
    "phone":"263",
    "postal code format":"",
    "postal code regex":"",
    "languages":"en-ZW,sn,nr,nd"
  }
];
